# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub(object):
    """--- DEFINIÇÃO DO SERVIÇO (RPCs) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarUsuario = channel.unary_unary(
                '/streaming.StreamingService/RegistrarUsuario',
                request_serializer=streaming__pb2.RegistrarUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/streaming.StreamingService/Login',
                request_serializer=streaming__pb2.LoginRequest.SerializeToString,
                response_deserializer=streaming__pb2.Usuario.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/streaming.StreamingService/ListarUsuarios',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaUsuarios.FromString,
                _registered_method=True)
        self.CriarMusica = channel.unary_unary(
                '/streaming.StreamingService/CriarMusica',
                request_serializer=streaming__pb2.CriarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.Musica.FromString,
                _registered_method=True)
        self.ListarMusicas = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicas',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicas.FromString,
                _registered_method=True)
        self.CriarPlaylist = channel.unary_unary(
                '/streaming.StreamingService/CriarPlaylist',
                request_serializer=streaming__pb2.CriarPlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.AdicionarMusicaPlaylist = channel.unary_unary(
                '/streaming.StreamingService/AdicionarMusicaPlaylist',
                request_serializer=streaming__pb2.AdicionarMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.MensagemSucesso.FromString,
                _registered_method=True)
        self.ObterPlaylist = channel.unary_unary(
                '/streaming.StreamingService/ObterPlaylist',
                request_serializer=streaming__pb2.BuscaPorIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.Playlist.FromString,
                _registered_method=True)
        self.ListarPlaylistsUsuario = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsUsuario',
                request_serializer=streaming__pb2.BuscaPorUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)
        self.ListarPlaylistsDaMusica = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsDaMusica',
                request_serializer=streaming__pb2.BuscaPorIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """--- DEFINIÇÃO DO SERVIÇO (RPCs) ---

    """

    def RegistrarUsuario(self, request, context):
        """Autenticação e Usuários
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarMusica(self, request, context):
        """Músicas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPlaylist(self, request, context):
        """Playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdicionarMusicaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObterPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsDaMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarUsuario,
                    request_deserializer=streaming__pb2.RegistrarUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=streaming__pb2.LoginRequest.FromString,
                    response_serializer=streaming__pb2.Usuario.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaUsuarios.SerializeToString,
            ),
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=streaming__pb2.CriarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.Musica.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaMusicas.SerializeToString,
            ),
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=streaming__pb2.CriarPlaylistRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'AdicionarMusicaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AdicionarMusicaPlaylist,
                    request_deserializer=streaming__pb2.AdicionarMusicaRequest.FromString,
                    response_serializer=streaming__pb2.MensagemSucesso.SerializeToString,
            ),
            'ObterPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterPlaylist,
                    request_deserializer=streaming__pb2.BuscaPorIdRequest.FromString,
                    response_serializer=streaming__pb2.Playlist.SerializeToString,
            ),
            'ListarPlaylistsUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsUsuario,
                    request_deserializer=streaming__pb2.BuscaPorUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
            'ListarPlaylistsDaMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsDaMusica,
                    request_deserializer=streaming__pb2.BuscaPorIdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """--- DEFINIÇÃO DO SERVIÇO (RPCs) ---

    """

    @staticmethod
    def RegistrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/RegistrarUsuario',
            streaming__pb2.RegistrarUsuarioRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/Login',
            streaming__pb2.LoginRequest.SerializeToString,
            streaming__pb2.Usuario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarUsuarios',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaUsuarios.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarMusica',
            streaming__pb2.CriarMusicaRequest.SerializeToString,
            streaming__pb2.Musica.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicas',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaMusicas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarPlaylist',
            streaming__pb2.CriarPlaylistRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdicionarMusicaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AdicionarMusicaPlaylist',
            streaming__pb2.AdicionarMusicaRequest.SerializeToString,
            streaming__pb2.MensagemSucesso.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObterPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ObterPlaylist',
            streaming__pb2.BuscaPorIdRequest.SerializeToString,
            streaming__pb2.Playlist.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsUsuario',
            streaming__pb2.BuscaPorUsuarioRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsDaMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsDaMusica',
            streaming__pb2.BuscaPorIdRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
