create table public.playlist(
    id bigint generated by default as identity primary key, 
    nome text not null,
    usuario_id uuid references public.usuario(id) on delete cascade not null
);

alter table public.playlist enable row level security;

create policy "Liberar Playlists" 
on public.playlist 
for all 
using (true) 
with check (true);

create table public.musica (
  id bigint generated by default as identity primary key, 
  nome text not null,    
  artista text not null   
);

alter table public.musica enable row level security;

create policy "Liberar Musicas" 
on public.musica 
for all 
using (true) 
with check (true);

create table public.playlist_musica (
  id bigint generated by default as identity primary key,
  
  playlist_id bigint references public.playlist(id) on delete cascade not null,
  
  musica_id bigint references public.musica(id) on delete cascade not null,
  
  unique(playlist_id, musica_id)
);

alter table public.playlist_musica enable row level security;

create policy "Liberar Juncao" 
on public.playlist_musica 
for all 
using (true) 
with check (true);