DROP TABLE IF EXISTS public.playlist_musica;

create table public.playlist_musica (
  id bigint generated by default as identity primary key,
  
  playlist_id bigint references public.playlist(id) on delete cascade not null,
  
  musica_id bigint references public.musica(id) on delete cascade not null,
  
  unique(playlist_id, musica_id)
);

alter table public.playlist_musica enable row level security;

create policy "Liberar Juncao" 
on public.playlist_musica 
for all 
using (true) 
with check (true);